# Generated by Django 3.2.6 on 2021-08-17 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('division', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to='posts/')),
                ('date', models.DateTimeField(auto_now=True, null=True)),
                ('paid', models.IntegerField(null=True)),
                ('desc', models.CharField(max_length=256)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='division.team')),
            ],
        ),
    ]
