# Generated by Django 3.2.6 on 2021-08-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0003_auto_20210822_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='desc',
            field=models.TextField(),
        ),
    ]
