# Generated by Django 3.2.6 on 2021-08-22 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eng', '0004_alter_review_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='linked',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='eng.post'),
        ),
    ]
