# Generated by Django 3.2.6 on 2021-08-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='userId',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
