# Generated by Django 3.2.6 on 2021-08-18 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0002_team_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='population',
        ),
        migrations.RemoveField(
            model_name='team',
            name='userId',
        ),
        migrations.AddField(
            model_name='team',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
