# Generated by Django 3.2.6 on 2021-08-23 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0003_auto_20210818_2354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('send_date', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=128, null=True)),
                ('desc', models.TextField()),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='division.team')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='division.team')),
            ],
        ),
    ]
