# Generated by Django 3.2.6 on 2021-08-23 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('division', '0004_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
